// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz2a2JRl5DhqO4SEwtZ-SXTxByW9ODSoU',
    appId: '1:631972301685:web:fe3a9d31878ed7003de13c',
    messagingSenderId: '631972301685',
    projectId: 'naqla-d42d2',
    authDomain: 'naqla-d42d2.firebaseapp.com',
    databaseURL: 'https://naqla-d42d2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'naqla-d42d2.appspot.com',
    measurementId: 'G-KFGS8W34QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWRZ3SONosQRbDgCsbroYZR3vQrs9ytfs',
    appId: '1:631972301685:android:b4d749f44072ceec3de13c',
    messagingSenderId: '631972301685',
    projectId: 'naqla-d42d2',
    databaseURL: 'https://naqla-d42d2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'naqla-d42d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0wJS2TgYvKeXDVSRhVV5uyHtPXluR9G8',
    appId: '1:631972301685:ios:3a73e042243b47243de13c',
    messagingSenderId: '631972301685',
    projectId: 'naqla-d42d2',
    databaseURL: 'https://naqla-d42d2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'naqla-d42d2.appspot.com',
    iosBundleId: 'com.example.graduation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0wJS2TgYvKeXDVSRhVV5uyHtPXluR9G8',
    appId: '1:631972301685:ios:3a73e042243b47243de13c',
    messagingSenderId: '631972301685',
    projectId: 'naqla-d42d2',
    databaseURL: 'https://naqla-d42d2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'naqla-d42d2.appspot.com',
    iosBundleId: 'com.example.graduation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz2a2JRl5DhqO4SEwtZ-SXTxByW9ODSoU',
    appId: '1:631972301685:web:4ab7f230e53bd1283de13c',
    messagingSenderId: '631972301685',
    projectId: 'naqla-d42d2',
    authDomain: 'naqla-d42d2.firebaseapp.com',
    databaseURL: 'https://naqla-d42d2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'naqla-d42d2.appspot.com',
    measurementId: 'G-FC7DYBC7KE',
  );
}
